#!/bin/bash
#PBS -N diggingForGoldHannes
#PBS -q serial
#PBS -l select=1:ncpus=10
#PBS -P CSCI1166
#PBS -l walltime=1:00:00
#PBS -M u19049014@tuks.co.za

cd /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold || exit

echo $PBS_JOBID

module load chpc/python/anaconda/3-2021.11

source /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold/job_env/bin/activate

python3 -pip install -r requirements.txt