#!/bin/bash
#PBS -l ncpus=8:ngpus=1
#PBS -P CSCI1166
#PBS -q gpu_1
#PBS -l walltime=4:00:00
#PBS -o /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold/run/0/output.out
#PBS -e /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold/run/0/output.err
#PBS -M u19049014@tuks.co.za

cd /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold || exit

source /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold/job_env/bin/activate