#!/bin/bash
#PBS -N diggingForGoldHannes
#PBS -q gpu_1
#PBS -l select=1:ncpus=8:ngpus=1
#PBS -P CSCI1166
#PBS -l walltime=4:00:00
#PBS -M u19049014@tuks.co.za

cd /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold || exit

echo $PBS_JOBID

module load chpc/python/anaconda/3-2021.11
module load chpc/cuda/11.6/PCIe/11.6

source /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold/job_env/bin/activate

python3 main.py