#!/bin/bash
#PBS -N diggingForGoldHannes
#PBS -q gpu_4
#PBS -l select=1:ncpus=40:ngpus=4
#PBS -P CSCI1166
#PBS -l walltime=12:00:00
#PBS -M u19049014@tuks.co.za

cd /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold || exit

echo $PBS_JOBID

module load chpc/python/anaconda/3-2021.11

source /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold/job_env/bin/activate

python3 mlp_2_hidden_analysis.py &
python3 mlp_4_hidden_analysis.py &
python3 mlp_4_hidden_fashionmnist_analysis.py &
python3 mlp_6_hidden_fashionmnist_analysis.py &
wait