#!/bin/bash
#PBS -N diggingForGoldHannes
#PBS -q gpu_3
#PBS -l select=1:ncpus=30:ngpus=3
#PBS -P CSCI1166
#PBS -l walltime=12:00:00
#PBS -M u19049014@tuks.co.za

cd /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold || exit

echo $PBS_JOBID

module load chpc/python/anaconda/3-2021.11

source /mnt/lustre/users/hkirsten/DiggingForGold/digging_for_gold/job_env/bin/activate

python3 small_cnn_mnist.py &
python3 small_cnn_cifar10.py &
python3 mlp_10_hidden_cifar10.py &
wait