from experiments.mlp_2_hidden_mnist.model import Mlp2Hidden
from experiments.mlp_4_hidden_mnist.model import Mlp4Hidden
from experiments.mlp_10_hidden_cifar10.model import Mlp10Hidden
from experiments.small_cnn_cifar10.model import SmallCNN
from experiments.alex_cnn_cifar10.model import AlexNet
from experiments.small_cnn_mnist.model import SmallCNNMnist
from experiments.mlp_4_hidden_fashionmnist.model import Mlp4HiddenFashionMnist
from experiments.mlp_6_hidden_fashionmnist.model import Mlp6HiddenFashionMnist
